apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: kafka-cli
  namespace: aap
  labels:
    team: aap
  annotations:
    nais.io/read-only-file-system: "false"
spec:
  image: {{IMAGE}}
  replicas:
    min: 1
    max: 1
  kafka:
    pool: {{KAFKA}}
    streams: true
  resources:
    limits:
      cpu: 1000m
      memory: 2048Mi
    requests:
      cpu: 1000m
      memory: 2048Mi
  filesFrom:
    - secret: {{AIVEN_SECRET}}
      mountPath: /var/run/secrets
