apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: kafka-cli
  namespace: aap
  labels:
    team: aap
spec:
  image: confluentinc/confluent-cli:2.12.0
  kafka:
    pool: nav-dev
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 100m
      memory: 512Mi
