apiVersion: nais.io/v1alpha1
kind: Pod
metadata:
  name: kafka-cli
  namespace: aap
  labels:
    team: aap
spec:
  image: {{image}}
  kafka:
    pool: nav-dev
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 100m
      memory: 1024Mi
  stdin: true
  stdinOnce: true
  tty: true
  restartPolicy: Never
