apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: kafka-cli
  namespace: aap
  labels:
    team: aap
spec:
  image: {{image}}
  kafka:
    pool: nav-prod
    streams: true
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 1000m
      memory: 2048Mi
    requests:
      cpu: 1000m
      memory: 2048Mi
