name: Deploy

on:
  push:
    branches: [ main ]

  workflow_dispatch:
    inputs:
      environment:
        description: Select GCP environment
        required: true
        default: 'dev'
        options: [ 'dev', 'prod' ]
      aiven-secret:
        description: Aiven secret to mount, e.g aiven-vedtak-6rxv2sxp
        required: true

env:
  image: ghcr.io/${{ github.repository }}:${{ github.sha }}
  aiven-secret: ${{ github.event.inputs.aiven-secret }}
  kafka-pool: nav-${{ github.event.inputs.environment }}
  cluster: ${{ github.event.inputs.environment }}-gcp

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: styfle/cancel-workflow-action@0.9.1
      - uses: actions/checkout@v3
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v2.10.0
        with:
          push: true
          tags: ${{ env.image }},ghcr.io/navikt/${{ github.repository }}:latest

      - uses: nais/deploy/actions/deploy@v1
        env:
          RESOURCE: nais.yml
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          PRINT_PAYLOAD: true
