on:
  push:
    branches: [ main ]

env:
  VERSION: 2.12.0 # confluentinc/confluent-cli version
  SRC: confluentinc/confluent-cli
  DEST: ghcr.io/navikt/aap-kafka-cli/kafka-cli

jobs:
  re-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - run: docker manifest inspect ${{ env.SRC }}:${{ env.VERSION }}
      - run: docker pull ${{ env.SRC }}:${{ env.VERSION }}
      - run: docker tag ${{ env.SRC }}:${{ env.VERSION }} ${{ env.DEST }}:${{ env.VERSION }}
      - run: docker push ${{ env.DEST }}:${{ env.VERSION }}

  deploy:
    runs-on: ubuntu-latest
    needs: [ re-tag ]
    steps:
      - uses: actions/checkout@v3
      - uses: nais/deploy/actions/deploy@v1
        env:
          CLUSTER: dev-gcp
          RESOURCE: nais.yml
          VAR: image=${{ env.DEST }}:${{ env.VERSION }}
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          PRINT_PAYLOAD: true
