name: Deploy kafka-manager

on:
  push:
    branches:
      - 'main'
    paths:
      - '.nais/org-kafka-manager-dev.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy til dev-fss
    steps:
      - uses: nais/deploy/actions/deploy@v1
        env:
          RESOURCE: .nais/org-kafka-manager-dev.yml
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}