name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Select GCP environment
        required: true
        default: dev
        type: choice
        options:
          - dev
          - prod
      aiven-secret:
        description: Aiven secret med korrekte rettigheter to mount, f.eks. aiven-org-kafka-manager-cg37ax1v
        required: true

env:
  IMAGE: ghcr.io/${{ github.repository }}:${{ github.sha }}
  POOL: nav-${{ github.event.inputs.environment }}
  SECRET: ${{ github.event.inputs.aiven-secret }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy til ${{ github.event.inputs.environment }}-gcp
    permissions:
      contents: "read"
      id-token: "write"
    steps:
      - uses: styfle/cancel-workflow-action@0.11.0
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v4
        with:
          push: true
          tags: ${{env.IMAGE}},ghcr.io/navikt/${{ github.repository }}:latest

      - uses: nais/deploy/actions/deploy@v2
        env:
          RESOURCE: .nais/nais.yml
          PRINT_PAYLOAD: true
          CLUSTER: ${{ github.event.inputs.environment }}-gcp
          VAR: pool=${{ env.POOL }},secret=${{ env.SECRET }}
